### ISSUE TITLE
Elaborar Roadmap de papéis 

### ISSUE THREAD

**Issue by lucasmidlhey** [fga-eps-mds/2019.2-Git-Breakdown#38]
Definir roadmap para PO, Scrum Master e Devops para alinhar os stakeholders.

- [x] analisar brainstorm de ideias

- [x] organizar seguindo a hierarquia das funcionalidades

- [ ] validar com equipe
